# Generated by Django 2.0.2 on 2018-03-02 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180301_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
